export const homeObjOne = {
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Exclusive Notes',
    headline:'Notes Of All Chapter Of Each Subject Of Every Semester',
    description:'Get access to all your college notes in a tap!',
     buttonLabel:'Get Started',
    imgStart:false,
    img:require('../../images/svg-1.svg').default,
    alt:'pic',
    dark:true,
    primary:true,
    darkText:false
}
export const homeObjTwo = {
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Exclusive Notes',
    headline:'Notes Of All Chapter Of Each Subject Of Every Semester',
    description:'Get access to all your college notes in a tap!',
     buttonLabel:'Get Started',
    imgStart:true,
    img:require('../../images/1.jpg').default,
    alt:'pic',
    dark:false,
    primary:false,
    darkText:true
}
export const homeObjThree = {
    id:'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Exclusive Notes',
    headline:'Notes Of All Chapter Of Each Subject Of Every Semester',
    description:'Get access to all your college notes in a tap!',
     buttonLabel:'Get Started',
    imgStart:false,
    img:require('../../images/1.jpg').default,
    alt:'pic',
    dark:false,
    primary:false,
    darkText:true,
}